# Generated by Django 5.0.7 on 2024-07-28 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("heading", models.CharField(max_length=255)),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
                ("date_got", models.DateTimeField(null=True)),
                ("content", models.TextField()),
                (
                    "files",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="maills.file"
                    ),
                ),
            ],
        ),
    ]
