# Generated by Django 5.0.7 on 2024-07-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maills", "0002_email_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="type",
            field=models.CharField(default="gmail.com", max_length=255),
        ),
    ]
