# Generated by Django 5.0.7 on 2024-07-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maills", "0004_message_email_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="email",
        ),
        migrations.AddField(
            model_name="email",
            name="messages",
            field=models.ManyToManyField(default=1, to="maills.message"),
        ),
    ]
