# Generated by Django 5.0.7 on 2024-07-29 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maills", "0005_remove_message_email_email_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="files",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="maills.file"
            ),
        ),
    ]
