# Generated by Django 5.0.7 on 2024-07-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maills", "0007_message_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date_got",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="date_sent",
            field=models.DateTimeField(null=True),
        ),
    ]
