# Generated by Django 5.0.7 on 2024-07-30 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maills", "0010_alter_file_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="maills.message",
            ),
        ),
    ]
