# Generated by Django 5.0.7 on 2024-07-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maills", "0011_alter_file_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="messages",
            field=models.ManyToManyField(related_name="emails", to="maills.message"),
        ),
    ]
